server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
   name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s

springdoc:
  swagger-ui:
   urls:
    - name: auth-service
      url: http://localhost:8084/v1/auth/v3/api-docs
    - name: crm-left-service
      url: http://localhost:8085/v1/crm/v3/api-docs
  api-docs:
    path: /v3/api-docs


application-title: Gateway Service
application-description: Gateway Left Service API Documentation
application-version: 1.0.0
application-license: Apache 2.0
