spring:
  application:
    name: file-service
  config:
    import: "optional:configserver:http://localhost:8088"
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB
  datasource:
    url: jdbc:postgresql://localhost:5432/file_service
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  base-url : https://localhost:8060/v1/file-storage
  port: 8082

photo:
  upload:
    path  : src/main/resources/photo-uploads

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0