spring:
  application:
    name: file-service
  config:
    import: "optional:configserver:http://localhost:8088"
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB
  datasource:
    url: jdbc:postgresql://localhost:5432/file_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  base-url : https://localhost:8060/v1/file-storage

photo:
  upload:
    path  : src/main/resources/photo-uploads