spring:
  application:
    name: project-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://localhost:5432/project_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8060


springdoc:
  application-title: Project Service API
