spring:
  application:
    name: crm-left-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_left_service
    password: 1234
    username: postgres